my_list = [ 1,2,3,'apple','lemon']
my_list.append(6)
print(my_list)
my_list.insert(1,20)
print(my_list)
my_list.remove(3)
print(my_list)
my_list.pop()
print(my_list)
my_list.sort(key= str)
print(my_list)
print()
my_list.reverse()
print(my_list)
print()
